module.exports = {
  apps: [
    {
      name: 'bot-cesta-topk',
      cwd: './packages/bots/cesta-topk',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'bot-liquidity-maker',
      cwd: './packages/bots/liquidity-maker',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'bot-endgame-carry',
      cwd: './packages/bots/endgame-carry',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'bot-espejo-smart',
      cwd: './packages/bots/espejo-smart',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'dashboard-api',
      cwd: './packages/dashboard/api',
      script: 'dist/server.js',
      instances: 1,
      autorestart: true,
      env: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'heartbeat-daemon',
      cwd: './packages/core',
      script: 'dist/heartbeat-daemon.js',
      instances: 1,
      autorestart: true,
      max_restarts: 20,
      min_uptime: '5s',
      env: { NODE_ENV: 'production' },
    },
  ],
};
